title: CR Formula Wiki
description: A wiki for CR formula and all of it's projects
theme: just-the-docs

url: https://cr-formula.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
